apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: gitops-container
        image: 142039336074.dkr.ecr.ap-south-1.amazonaws.com/gitops-app:latest
        ports:
        - containerPort: 5000
